### ISSUE TITLE
java.util.ConcurrentModificationException when using restful api

### ISSUE THREAD

**Issue by maysamyabandeh** [mesos/myriad#19]
https://github.com/mesos/myriad/blob/phase1/src/main/java/com/ebay/myriad/scheduler/event/handlers/StatusUpdateEventHandler.java#L60 does not safely access the list of pending tasks.

                schedulerState.makeTaskActive(taskId);

causing 

ava.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at com.ebay.myriad.scheduler.event.handlers.ResourceOffersEventHandler.onEvent(ResourceOffersEventHandler.java:68)
	at com.ebay.myriad.scheduler.event.handlers.ResourceOffersEventHandler.onEvent(ResourceOffersEventHandler.java:38)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adam-mesos** [comment]
Fixed in https://github.com/mesos/myriad/commit/c0fe6b7690aa2facd960fbe99f40c57557105eca
